// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EYXMx-Bkvuv7EY6V9OBxeQemAz_JSrE',
    appId: '1:694581275464:web:aec6d0f9b48aded90ae17d',
    messagingSenderId: '694581275464',
    projectId: 'loginsignup-cejas',
    authDomain: 'loginsignup-cejas.firebaseapp.com',
    storageBucket: 'loginsignup-cejas.firebasestorage.app',
    measurementId: 'G-9ZXPXDTX5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8UGQqahnIrKde_Qgi38JSXd-kOd8T0bc',
    appId: '1:694581275464:android:9701921e17220c670ae17d',
    messagingSenderId: '694581275464',
    projectId: 'loginsignup-cejas',
    storageBucket: 'loginsignup-cejas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFaX3UKsiw5MasUvTVSTg_Z407lAXmIA',
    appId: '1:694581275464:ios:b8b43559db940d3d0ae17d',
    messagingSenderId: '694581275464',
    projectId: 'loginsignup-cejas',
    storageBucket: 'loginsignup-cejas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFaX3UKsiw5MasUvTVSTg_Z407lAXmIA',
    appId: '1:694581275464:ios:b8b43559db940d3d0ae17d',
    messagingSenderId: '694581275464',
    projectId: 'loginsignup-cejas',
    storageBucket: 'loginsignup-cejas.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EYXMx-Bkvuv7EY6V9OBxeQemAz_JSrE',
    appId: '1:694581275464:web:1dabe6e7c61293d30ae17d',
    messagingSenderId: '694581275464',
    projectId: 'loginsignup-cejas',
    authDomain: 'loginsignup-cejas.firebaseapp.com',
    storageBucket: 'loginsignup-cejas.firebasestorage.app',
    measurementId: 'G-FB5LCGBZQ6',
  );
}
